Repository Hows-the-Air-Today/HAT-backend-spring-boot, pull requests merged in 2023-05, with the labels that each got.

#81 👷 ci(HAT-383): 개발용 도커파일 추가
  air-quality-app-batch/Dockerfile-dev
  air-quality-app-external-api/Dockerfile-dev
  community-app-external-api/Dockerfile-dev
  member-app-external-api/Dockerfile-dev
Labels: 🌏 Deploy, ⚙ Setting

#83 🐛 fix(HAT-389): 게시물 상세보기 리턴값 수정
  community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostService.java
Labels: 🔰BE, 🐞 BugFix

#84 ✅ test(HAT-394): 게시글 컨트롤러 작성
  community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/controller/PostControllerTest.java
Labels: 🔰BE, 📬 API, ✅ Test

#85 ✅ test(HAT-395): 댓글, 좋아요 컨트롤러 테스트
  community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/controller/CommentControllerTest.java
  community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/controller/LikeControllerTest.java
Labels: 🔰BE, 📬 API, ✅ Test

#86 📝 docs: README 업데이트
  README.md
Labels: 🔰BE, 📃 Docs
