Repository Hows-the-Air-Today/HAT-backend-spring-boot, pull requests merged in 2023-03, with the labels that each got.

#6 🚑 fix(HAT-141): QueryDSL 설정 변경
  air-quality-domain-rds/build.gradle
  community-domain-rds/build.gradle
  member-domain-rds/build.gradle
Labels: 🔰BE, 📚 DB, 🐞 BugFix, ⚙ Setting

#10 👷 ci(HAT-151): Super-Linter 코드 분석 규칙 수정
  .github/workflows/linter.yaml
  .github/workflows/linters/naver-checkstyle-rules.xml
Labels: ⚙ Setting

#11 👷 ci(HAT-152): 구글 자바 포맷 비활성화
  .github/workflows/linter.yaml
Labels: ⚙ Setting

#9 ✨ feat(HAT-142): Spring Security Setting
  build.gradle
  member-app-external-api/build.gradle
  member-app-external-api/src/main/java/io/howstheairtoday/AppMemberExternalApiApplication.java
  member-app-external-api/src/main/java/io/howstheairtoday/appmemberexternalapi/AppMemberExternalApiApplication.java
  member-app-external-api/src/main/java/io/howstheairtoday/appmemberexternalapi/config/CustomSecurityConfig.java
  member-app-external-api/src/main/java/io/howstheairtoday/appmemberexternalapi/config/RootConfig.java
  member-app-external-api/src/main/java/io/howstheairtoday/appmemberexternalapi/service/MemberDetailsService.java
  member-app-external-api/src/main/java/io/howstheairtoday/appmemberexternalapi/service/dto/MemberLoginRequestDTO.java
  member-app-external-api/src/main/java/io/howstheairtoday/appmemberexternalapi/service/handler/MemberLoginSuccessHandler.java
  member-app-external-api/src/main/resources/application.yaml
  member-domain-rds/build.gradle
  member-domain-rds/src/main/java/io/howstheairtoday/memberdomainrds/entity/BaseTimeEntity.java
  member-domain-rds/src/main/java/io/howstheairtoday/memberdomainrds/entity/LoginRole.java
  member-domain-rds/src/main/java/io/howstheairtoday/memberdomainrds/entity/LoginType.java
  member-domain-rds/src/main/java/io/howstheairtoday/memberdomainrds/entity/Member.java
  member-domain-rds/src/main/java/io/howstheairtoday/memberdomainrds/repository/MemberRepository.java
  member-domain-rds/src/test/java/io/howstheairtoday/memberdomainrds/MemberDomainRdsApplicationTests.java
  member-domain-rds/src/test/java/io/howstheairtoday/memberdomainrds/repository/MemberRepositoryTest.java
  module-core/build.gradle
  module-core/src/main/java/io/howstheairtoday/modulecore/ModuleCoreApplication.java
  module-core/src/main/java/io/howstheairtoday/modulecore/security/filter/MemberLoginFilter.java
Labels: 🔰BE, ✨ Feature, ⚙ Setting

#17 👷 ci(HAT-154): 도커파일 추가
  air-quality-app-batch/Dockerfile
  air-quality-app-external-api/Dockerfile
  community-app-external-api/Dockerfile
  member-app-external-api/Dockerfile
Labels: 🌏 Deploy

#16 ✨ feat(HAT-78): 대기질 실시간 측정정보 가공
  air-quality-app-batch/src/main/java/io/howstheairtoday/service/AirQualityRealTimeService.java
  air-quality-app-batch/src/test/java/io/howstheairtoday/airqualityappbatch/service/ServiceTests.java
Labels: 🔰BE, 📬 API, ✨ Feature, ✅ Test

#13 ✨ feat(HAT-69): 게시글작성기능
  build.gradle
  community-app-external-api/build.gradle
  community-app-external-api/src/main/java/io/howstheairtoday/AppCommunityExternalApiApplication.java
  community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/common/ApiResponse.java
  community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/controller/PostController.java
  community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/exception/ValidExceptionController.java
  community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostService.java
  community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/dto/request/PostRequestDto.java
  community-app-external-api/src/main/resources/application.yaml
  community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/service/ExternalPostServiceTest.java
  community-domain-rds/build.gradle
  community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/CommunityDomainRdsApplication.java
  community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/common/BaseTimeEntity.java
  community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/entity/Post.java
  community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/entity/PostImage.java
  community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/repository/PostRepository.java
  community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/service/DomainCommunityService.java
  community-domain-rds/src/test/java/io/howstheairtoday/communitydomainrds/CommunityDomainRdsApplicationTests.java
  community-domain-rds/src/test/java/io/howstheairtoday/communitydomainrds/repository/PostRepositoryTest.java
Labels: 🔰BE, 📬 API, ✨ Feature, ✅ Test

#20 🐛 fix(HAT-78): 대기질 실시간 측정정보 가공
  air-quality-app-batch/src/main/java/io/howstheairtoday/service/AirQualityRealTimeService.java
  air-quality-app-batch/src/main/java/io/howstheairtoday/service/dto/response/CurrentDustResponseDTO.java
  air-quality-app-batch/src/test/java/io/howstheairtoday/airqualityappbatch/service/ServiceTests.java
  air-quality-domain-rds/src/main/java/io/howstheairtoday/airqualitydomainrds/entity/AirQualityRealTime.java
Labels: 🔰BE, 📬 API, 🐞 BugFix

#24 📌 build: manifest attribute 정의
  air-quality-app-batch/build.gradle
  air-quality-app-external-api/build.gradle
  community-app-external-api/build.gradle
  member-app-external-api/build.gradle
Labels: 🔰BE, 🌏 Deploy, ⚙ Setting

#22 ✨ feat(HAT-54): 게시물 댓글 작성 기능
  build.gradle
  community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/controller/CommentController.java
  community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/CommentService.java
  community-app-external-api/src/main/java/io/howstheairtoday/appcommunityexternalapi/service/dto/request/CommentRequestDTO.java
  community-app-external-api/src/test/java/io/howstheairtoday/appcommunityexternalapi/service/CommentServiceTest.java
  community-domain-rds/build.gradle
  community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/entity/Comment.java
  community-domain-rds/src/main/java/io/howstheairtoday/communitydomainrds/repository/CommentRepository.java
  community-domain-rds/src/test/java/io/howstheairtoday/communitydomainrds/repository/CommentTest.java
Labels: 🔰BE, 📬 API, ✨ Feature, ✅ Test

#23 ✨ feat(HAT-77): 대기질 실시간 측정정보 삽입
  air-quality-app-batch/src/main/java/io/howstheairtoday/service/AirQualityRealTimeService.java
  air-quality-app-batch/src/test/java/io/howstheairtoday/airqualityappbatch/AirQualityAppBatchApplicationTests.java
  air-quality-app-batch/src/test/java/io/howstheairtoday/airqualityappbatch/service/ServiceTests.java
  air-quality-domain-rds/src/main/java/io/howstheairtoday/airqualitydomainrds/entity/AirQualityRealTime.java
  air-quality-domain-rds/src/test/java/io/howstheairtoday/airqualitydomainrds/RepositoryTests.java
Labels: 🔰BE, 📬 API, 📚 DB, ✨ Feature, ✅ Test
